# Generated by Django 4.1.6 on 2024-02-03 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('hack_uid', models.PositiveIntegerField(unique=True, verbose_name='HackAPI Unique ID')),
                ('username', models.CharField(max_length=100, verbose_name='Username')),
                ('avatar', models.JSONField(default=dict, verbose_name='Avatar')),
                ('texts', models.JSONField(default=dict, verbose_name='Texts')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='AuthorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Name')),
                ('platform', models.CharField(blank=True, max_length=100, verbose_name='Platform')),
            ],
            options={
                'verbose_name': 'Author Info',
            },
        ),
        migrations.CreateModel(
            name='AuthorStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('followers', models.PositiveIntegerField(default=0, verbose_name='Followers')),
            ],
            options={
                'verbose_name': 'Author Stats',
            },
        ),
        migrations.CreateModel(
            name='ContentStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Likes')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Views')),
                ('comments', models.PositiveIntegerField(default=0, verbose_name='Comments')),
            ],
            options={
                'verbose_name': 'Content Stats',
            },
        ),
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('main_text', models.TextField(blank=True, verbose_name='Main Text')),
                ('token_count', models.PositiveIntegerField(default=0, verbose_name='Token count')),
                ('char_count', models.PositiveIntegerField(default=0, verbose_name='Character count')),
                ('tag_count', models.PositiveIntegerField(default=0, verbose_name='Tag count')),
            ],
            options={
                'verbose_name': 'Context',
                'verbose_name_plural': 'Contexts',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('urls', models.JSONField(default=list, verbose_name='Urls')),
                ('media_type', models.CharField(default='IMAGE', max_length=20, verbose_name='Media type')),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Medias',
            },
        ),
        migrations.CreateModel(
            name='OriginDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('origin_platform', models.CharField(max_length=25, verbose_name='Origin platform')),
                ('origin_url', models.URLField(blank=True, verbose_name='Origin URL')),
            ],
            options={
                'verbose_name': 'Origin Details',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('hack_uid', models.PositiveIntegerField(unique=True, verbose_name='HackAPI Unique ID')),
                ('originally_created_at', models.DateTimeField(blank=True, null=True, verbose_name='Originally created at')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='social_content.author', verbose_name='Author')),
                ('context', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='social_content.context', verbose_name='Context')),
                ('media', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='social_content.media', verbose_name='Media')),
                ('origin_details', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='social_content.origindetails', verbose_name='Origin Details')),
                ('stats', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='social_content.contentstats', verbose_name='Content Stats')),
            ],
            options={
                'verbose_name': 'Content',
                'verbose_name_plural': 'Contents',
            },
        ),
        migrations.AddField(
            model_name='author',
            name='info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='social_content.authorinfo', verbose_name='Info'),
        ),
        migrations.AddField(
            model_name='author',
            name='stats',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='social_content.authorstats', verbose_name='Stats'),
        ),
    ]
